In [1]:
import pandas as pd
import numpy as np
import json

import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# json → python dictionary & list → dataframe:
'''gives more control,
lets you inspect raw structure,
useful for nested JSONs later'''

with open(r"C:\Users\kadit\MedicalPlan-Xray\data\raw\data.json")as file:
    data = json.load(file)
    
df = pd.DataFrame(data)
df

,user_id,gender,age,state_tier,occupation_class,salary_bracket,total_income_inr,is_smoker,family_members,medical_plan,annual_expenditure_inr
0,1,Male,19,Tier-2,Low-Risk,Tier-1,203736,0,5,Medium,89149
1,2,Female,20,Tier-1,Low-Risk,Tier-2,527824,0,6,Medium,115346
2,3,Male,46,Tier-2,High-Risk,Tier-1,233707,0,3,High,128494
3,4,Male,66,Tier-1,Low-Risk,Tier-1,330331,0,1,Medium,126971
4,5,Male,42,Tier-1,Low-Risk,Tier-2,879201,0,6,Medium,142701
...,...,...,...,...,...,...,...,...,...,...,...
975,996,Male,40,Tier-3,Medium-Risk,Tier-1,234109,0,3,Low,54431
976,997,Female,53,Tier-1,Low-Risk,Tier-2,1124310,0,6,High,142431
977,998,Male,26,Tier-2,Low-Risk,Tier-1,412093,0,2,Low,48431
978,999,Female,57,Tier-1,Low-Risk,Tier-2,789421,1,4,High,184310
979,1000,Male,34,Tier-2,Low-Risk,Tier-1,412093,0,6,High,124310

In [ ]:
df.shape

# 980 rows, 11 columns
# 980 observations, 11 features (columns)

(980, 11)

In [ ]:
df.columns # FYI 1. here in this project our target variable is "medical_plan" and rest are features which we will use to predict the target variable.

Index(['user_id', 'gender', 'age', 'state_tier', 'occupation_class',
       'salary_bracket', 'total_income_inr', 'is_smoker', 'family_members',
       'medical_plan', 'annual_expenditure_inr'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 980 non-null    int64
 1   gender                  980 non-null    str
 2   age                     980 non-null    int64
 3   state_tier              980 non-null    str
 4   occupation_class        980 non-null    str
 5   salary_bracket          980 non-null    str
 6   total_income_inr        980 non-null    int64
 7   is_smoker               980 non-null    int64
 8   family_members          980 non-null    int64
 9   medical_plan            980 non-null    str
 10  annual_expenditure_inr  980 non-null    int64
dtypes: int64(6), str(5)
memory usage: 113.9 KB

In [16]:
df.describe()

,user_id,age,total_income_inr,is_smoker,family_members,annual_expenditure_inr
count,980.000000,980.000000,9.800000e+02,980.000000,980.000000,980.000000
mean,505.314286,45.778571,9.241866e+05,0.213265,3.527551,134662.093878
std,287.731196,16.279509,8.652394e+05,0.409823,1.709869,65517.903020
min,1.000000,18.000000,1.519340e+05,0.000000,1.000000,5000.000000
25%,262.750000,32.000000,4.117075e+05,0.000000,2.000000,84310.000000
50%,507.500000,45.000000,7.894210e+05,0.000000,3.500000,124310.000000
75%,753.250000,60.000000,1.124310e+06,0.000000,5.000000,184096.750000
max,1000.000000,75.000000,4.997509e+06,1.000000,6.000000,416505.000000

In [109]:
df.to_csv("../data/interim/raw_loaded.csv", index=False)